import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { login, signup } from "../services/api";
import { useUser } from "../context/UserContext";
export default function AuthPage(){
 const [mode,setMode]=useState("login"),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""); const nav=useNavigate(); const {login:saveLogin}=useUser();
 const submit=async e=>{e.preventDefault();setBusy(true);setError("");setNotice("");try{if(mode==="signup"){const r=await signup({name,email,password});setNotice(r.message);setMode("login");setPassword("");}else{const r=await login({email,password});saveLogin(r);nav("/explore");}}catch(err){setError(err.message)}finally{setBusy(false)}};
 return <main className="flex min-h-screen items-center justify-center bg-[#faf9f7] px-5 py-10"><div className="w-full max-w-md rounded-3xl border bg-white p-7 shadow-sm"><Link to="/" className="font-serif text-lg font-bold">✦ SkillPilot</Link><h1 className="mt-8 font-serif text-3xl font-bold">{mode==="login"?"Welcome back":"Create your account"}</h1><p className="mt-2 text-sm text-gray-500">Your assessments, chats, skill gaps and roadmap progress are saved to your account.</p>
 <div className="mt-6 flex rounded-xl bg-gray-100 p-1"><button onClick={()=>{setMode("signup");setError("");setNotice("")}} className={`flex-1 rounded-lg py-2 text-sm ${mode==="signup"?"bg-white shadow":"text-gray-500"}`}>Sign up</button><button onClick={()=>{setMode("login");setError("");setNotice("")}} className={`flex-1 rounded-lg py-2 text-sm ${mode==="login"?"bg-white shadow":"text-gray-500"}`}>Log in</button></div>
 {notice&&<div className="mt-4 rounded-xl bg-green-50 p-3 text-xs text-green-700">{notice}</div>}{error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-xs text-red-600">{error}</div>}
 <form onSubmit={submit} className="mt-5 space-y-4">{mode==="signup"&&<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" className="h-11 w-full rounded-xl border px-3 text-sm outline-none focus:border-indigo-500"/>}<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" className="h-11 w-full rounded-xl border px-3 text-sm outline-none focus:border-indigo-500"/><input required minLength={6} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password (6+ characters)" className="h-11 w-full rounded-xl border px-3 text-sm outline-none focus:border-indigo-500"/><button disabled={busy} className="h-11 w-full rounded-xl bg-indigo-600 text-sm font-semibold text-white hover:bg-indigo-700 disabled:opacity-50">{busy?"Please wait…":mode==="login"?"Log in":"Create account"}</button></form>
 <p className="mt-5 text-center text-xs text-gray-400">Signing up creates the account only. You will be asked to log in.</p></div></main>;
}
