import { useEffect,useRef,useState } from "react";
import { useLocation,useNavigate } from "react-router-dom";
import { Bot,Check,Send,Plus,ArrowRight,History,MessageSquare,Loader2 } from "lucide-react";
import { getChatHistory,getChatSessions,replyChat,startChat } from "../services/api";
import { useUser } from "../context/UserContext";

export default function ChatPage(){
 const location=useLocation(),nav=useNavigate(),params=new URLSearchParams(location.search),requestedRole=params.get("role"),requestedSession=params.get("session"); const {target_role}=useUser();
 const [sessions,setSessions]=useState([]),[sessionId,setSessionId]=useState(requestedSession||null),[roleId,setRoleId]=useState(requestedRole||target_role||"data-scientist"),[messages,setMessages]=useState([]),[options,setOptions]=useState([]),[input,setInput]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[complete,setComplete]=useState(false); const initialized=useRef(false);
 const loadSessions=()=>getChatSessions().then(setSessions).catch(e=>setError(e.message));
 useEffect(()=>{if(initialized.current)return;initialized.current=true;loadSessions();if(requestedSession){getChatHistory(requestedSession).then(r=>{setSessionId(requestedSession);setMessages(r.messages.map(m=>({type:m.sender,text:m.message})));setComplete(sessions.find(x=>x.session_id===requestedSession)?.status==="complete")}).catch(e=>setError(e.message));return;}if(requestedRole){startNew(requestedRole);return;}getChatSessions().then(list=>{setSessions(list);const current=list.find(x=>x.status==="in_progress")||list[0];if(current) openSession(current);else startNew(target_role||"data-scientist")}).catch(()=>startNew(target_role||"data-scientist"))},[]);
 const startNew=async role=>{setBusy(true);setError("");try{const r=await startChat(role);setSessionId(r.session_id);setRoleId(r.role_id);setMessages(r.messages?.map(m=>({type:m.sender,text:m.message}))||[{type:"ai",text:r.message}]);setOptions(r.quick_replies||[]);setComplete(false);await loadSessions()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const openSession=async s=>{setBusy(true);setError("");try{const r=await getChatHistory(s.session_id);setSessionId(s.session_id);setRoleId(s.role_id);setMessages(r.messages.map(m=>({type:m.sender,text:m.message})));setComplete(s.status==="complete");setOptions([])}catch(e){setError(e.message)}finally{setBusy(false)}};
 const submit=async text=>{const answer=text.trim();if(!answer||busy||!sessionId)return;setMessages(m=>[...m,{type:"user",text:answer}]);setInput("");setBusy(true);setError("");try{const r=await replyChat(sessionId,answer);setMessages(m=>[...m,{type:"ai",text:r.message}]);setOptions(r.quick_replies||[]);setComplete(!!r.done);await loadSessions()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const roleTitle=roleId?.replaceAll("-"," ");
 return <main className="min-h-[calc(100vh-68px)] bg-[#f7f8fb]"><div className="mx-auto flex max-w-7xl gap-4 px-4 py-5 md:px-5">
  <aside className="hidden w-64 shrink-0 rounded-2xl border bg-white p-3 md:block"><button onClick={()=>startNew(target_role||"data-scientist")} className="flex w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 px-3 py-2.5 text-xs font-semibold text-white"><Plus size={14}/> New assessment</button><p className="mt-5 flex items-center gap-2 px-2 text-[10px] font-bold uppercase tracking-wider text-gray-400"><History size={12}/> Past chats</p><div className="mt-2 max-h-[65vh] space-y-1 overflow-y-auto">{sessions.map(s=><button key={s.session_id} onClick={()=>openSession(s)} className={`w-full rounded-xl p-3 text-left ${sessionId===s.session_id?"bg-indigo-50 text-indigo-700":"hover:bg-gray-50"}`}><div className="flex items-center gap-2"><MessageSquare size={13}/><span className="truncate text-xs font-semibold">{s.role_id.replaceAll("-"," ")}</span></div><p className="mt-1 text-[10px] text-gray-400">{new Date(s.updated_at).toLocaleDateString()} · {s.status}</p></button>)}</div></aside>
  <section className="min-w-0 flex-1"><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-indigo-600">AI COACH</p><h1 className="mt-2 font-serif text-3xl font-bold">Your {roleTitle} assessment</h1><p className="mt-1 text-sm text-gray-500">Past conversations stay here, just like a normal AI chat.</p></div><button onClick={()=>startNew(target_role||"data-scientist")} className="flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-xs font-semibold md:hidden"><Plus size={13}/> New</button></div>
   <div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="max-h-[58vh] space-y-4 overflow-y-auto p-5">{messages.length===0&&<div className="flex items-center gap-2 text-xs text-gray-400"><Loader2 className="animate-spin" size={14}/> Loading conversation…</div>}{messages.map((m,i)=><div key={i} className={`flex ${m.type==="user"?"justify-end":"justify-start"}`}><div className={`max-w-[84%] rounded-2xl px-4 py-3 text-sm leading-6 ${m.type==="user"?"bg-indigo-600 text-white":"bg-gray-100 text-gray-700"}`}>{m.type==="ai"&&<div className="mb-1 flex items-center gap-1 text-[10px] font-bold uppercase tracking-wider text-indigo-600"><Bot size={12}/> SkillPilot AI</div>}{m.text}</div></div>)}{busy&&<div className="text-xs text-gray-400">Thinking…</div>}{error&&<div className="rounded-lg bg-red-50 p-3 text-xs text-red-600">{error}</div>}</div>
    {!complete?<div className="border-t bg-gray-50 p-4"><p className="mb-2 text-[11px] font-semibold uppercase tracking-wider text-gray-400">Suggested replies</p><div className="flex flex-wrap gap-2">{options.map(o=><button key={o} disabled={busy} onClick={()=>submit(o)} className="rounded-full border bg-white px-3 py-2 text-xs font-medium hover:border-indigo-300 hover:text-indigo-600 disabled:opacity-50">{o}</button>)}</div><form onSubmit={e=>{e.preventDefault();submit(input)}} className="mt-3 flex gap-2"><input value={input} onChange={e=>setInput(e.target.value)} disabled={busy} placeholder="Or answer in your own words…" className="h-11 flex-1 rounded-xl border bg-white px-3 text-sm outline-none focus:border-indigo-500"/><button disabled={busy||!input.trim()} className="flex h-11 w-11 items-center justify-center rounded-xl bg-indigo-600 text-white disabled:opacity-40"><Send size={16}/></button></form></div>:<div className="border-t bg-gray-50 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold flex items-center gap-2"><Check size={15} className="text-green-600"/> Assessment saved</p><p className="text-xs text-gray-500">Choose what you want to explore next.</p></div><div className="flex gap-2"><button onClick={()=>nav("/skill-gap")} className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Skill Gap <ArrowRight className="ml-1 inline" size={14}/></button><button onClick={()=>nav("/roadmap")} className="rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold">Roadmap</button></div></div></div>}</div></section></div></main>;
}
