import { useEffect,useState } from "react";
import { useLocation,useNavigate } from "react-router-dom";
import { Bot,Check,Send,RotateCcw } from "lucide-react";
import { replyChat,startChat } from "../services/api";
import { useUser } from "../context/UserContext";

export default function ChatPage(){
 const location=useLocation(), nav=useNavigate(); const params=new URLSearchParams(location.search); const requestedRole=params.get("role");
 const {roleId,role,sessionId,setSession,clearSession}=useUser(); const activeRole=requestedRole||roleId||"data-scientist";
 const [messages,setMessages]=useState([]); const [options,setOptions]=useState([]); const [input,setInput]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{let cancelled=false; setBusy(true); setError(""); startChat(activeRole).then(r=>{if(cancelled)return;setSession({sessionId:r.session_id,roleId:activeRole,role:r.message.split(".")[0].replace("Let's calibrate your current depth for ","")});setMessages([{type:"ai",text:r.message}]);setOptions(r.quick_replies||[])}).catch(e=>{if(!cancelled)setError(e.message)}).finally(()=>!cancelled&&setBusy(false)); return()=>{cancelled=true};},[activeRole]);
 const submit=async(text)=>{const answer=text.trim();if(!answer||busy||!sessionId)return;setMessages(m=>[...m,{type:"user",text:answer}]);setInput("");setBusy(true);setError("");try{const r=await replyChat(sessionId,answer);setMessages(m=>[...m,{type:"ai",text:r.message}]);setOptions(r.quick_replies||[]);if(r.done){setTimeout(()=>nav("/skill-gap"),450)}}catch(e){setError(e.message)}finally{setBusy(false)}};
 const restart=()=>{clearSession();setMessages([]);setOptions([]);};
 return <main className="min-h-[calc(100vh-68px)] bg-[#fafafa]"><div className="mx-auto max-w-3xl px-5 py-10"><div className="mb-6 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-indigo-600">STEP 2 · CALIBRATE</p><h1 className="mt-2 font-serif text-3xl font-bold">Your skill-depth interview</h1><p className="mt-1 text-sm text-gray-500">{role||"Target role"} · {messages.filter(m=>m.type==="user").length} answers</p></div><button onClick={restart} className="flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-xs text-gray-500"><RotateCcw size={13}/> Restart</button></div>
 <div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="max-h-[55vh] space-y-4 overflow-y-auto p-5">{messages.map((m,i)=><div key={i} className={`flex ${m.type==="user"?"justify-end":"justify-start"}`}><div className={`max-w-[82%] rounded-2xl px-4 py-3 text-sm leading-6 ${m.type==="user"?"bg-indigo-600 text-white":"bg-gray-100 text-gray-700"}`}>{m.type==="ai"&&<div className="mb-1 flex items-center gap-1 text-[10px] font-bold uppercase tracking-wider text-indigo-600"><Bot size={12}/> SkillPilot</div>}{m.text}</div></div>)}{busy&&<div className="text-xs text-gray-400">Thinking…</div>}{error&&<div className="rounded-lg bg-red-50 p-3 text-xs text-red-600">{error}</div>}</div>
 <div className="border-t bg-gray-50 p-4"><div className="flex flex-wrap gap-2">{options.map(o=><button key={o} disabled={busy} onClick={()=>submit(o)} className="rounded-full border border-gray-200 bg-white px-3 py-2 text-xs font-medium text-gray-700 hover:border-indigo-300 hover:text-indigo-600 disabled:opacity-50">{o}</button>)}</div><form onSubmit={e=>{e.preventDefault();submit(input)}} className="mt-3 flex gap-2"><input value={input} onChange={e=>setInput(e.target.value)} disabled={busy} placeholder="Or type your own answer…" className="h-11 flex-1 rounded-lg border border-gray-200 bg-white px-3 text-sm outline-none focus:border-indigo-500"/><button disabled={busy||!input.trim()} className="flex h-11 w-11 items-center justify-center rounded-lg bg-indigo-600 text-white disabled:opacity-40"><Send size={16}/></button></form></div></div>
 <div className="mt-4 flex items-center gap-2 text-xs text-gray-400"><Check size={13}/> Your answers are used only to calibrate this demo session.</div></div></main>;
}
