import { Link } from "react-router-dom";
import { ArrowRight, Brain, Gauge, Route } from "lucide-react";

export default function LandingPage() {
  return <div className="min-h-screen bg-[#faf9f7]">
    <header className="border-b border-gray-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><Link to="/" className="font-serif text-xl font-bold">✦ SkillPilot</Link><div className="flex gap-5 text-sm"><Link to="/explore" className="text-gray-600">Explore</Link><Link to="/auth" className="font-semibold text-indigo-600">Log in</Link></div></div></header>
    <main>
      <section className="relative overflow-hidden border-b border-gray-200"><div className="absolute inset-0 opacity-40" style={{backgroundImage:"linear-gradient(#e5e7eb 1px, transparent 1px),linear-gradient(90deg,#e5e7eb 1px,transparent 1px)",backgroundSize:"40px 40px"}}/><div className="relative mx-auto grid max-w-6xl gap-12 px-5 py-20 md:grid-cols-2 md:items-center">
        <div><p className="mb-4 text-xs font-bold uppercase tracking-[.18em] text-indigo-600">AI-ERA CAREER INTELLIGENCE</p><h1 className="font-serif text-5xl font-bold leading-[1.05] md:text-6xl">Know what to learn.<br/><span className="text-indigo-600">Know how deep.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-gray-500">SkillPilot compares your current abilities with real occupation data and gives every skill a depth call: <b className="text-gray-800">Master</b>, <b className="text-gray-800">AI-Augment</b>, or <b className="text-gray-800">Basic-Awareness</b>.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/explore" className="flex items-center gap-2 rounded-lg bg-indigo-600 px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-indigo-100 hover:bg-indigo-700">Start analysis <ArrowRight size={16}/></Link><Link to="/explore" className="rounded-lg border border-gray-200 bg-white px-5 py-3 text-sm font-semibold text-gray-700">Browse roles</Link></div></div>
        <div className="rounded-2xl border border-gray-200 bg-white p-6 shadow-xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-sm font-bold">Example depth recommendations</h2><span className="rounded-full bg-gray-100 px-3 py-1 text-xs text-gray-500">Data Scientist</span></div>{[["Experiment Design","Human-Core","MASTER"],["Python & Programming","AI-Augmented","AI-AUGMENT"],["Routine Reporting","AI-Accelerated","BASIC-AWARENESS"]].map(([name,tier,depth])=><div key={name} className="flex items-center justify-between gap-4 border-b border-gray-100 py-4 last:border-0"><div><p className="text-sm font-semibold">{name}</p><p className="mt-1 text-xs text-gray-500">{tier}</p></div><span className="shrink-0 rounded bg-gray-900 px-2 py-1 text-[10px] font-bold text-white">{depth}</span></div>)}</div>
      </div></section>
      <section className="mx-auto max-w-6xl px-5 py-12"><div className="grid gap-4 md:grid-cols-3">{[[Brain,"Calibrate your skills","A short guided conversation turns your experience into measurable skill signals."],[Gauge,"Find the real gaps","Compare your level with the depth your target role actually needs."],[Route,"Build your roadmap","Get a focused 90-day plan instead of a giant generic course list."]].map(([Icon,title,text],i)=><div key={title} className="rounded-xl border border-gray-200 bg-white p-6"><Icon className="text-indigo-600" size={22}/><p className="mt-5 text-xs text-gray-400">0{i+1}</p><h3 className="mt-1 font-serif text-xl font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-gray-500">{text}</p></div>)}</div></section>
    </main>
  </div>;
}
