import { useEffect,useState } from "react";
import { useNavigate } from "react-router-dom";
import { Save, UserCircle, Target, Clock3, Sparkles } from "lucide-react";
import { getRoles, getMe, getCurrentSkillGap, getCurrentRoadmap, updateProfile } from "../services/api";
import { useUser } from "../context/UserContext";
export default function ProfilePage(){
 const user=useUser(),nav=useNavigate(); const [form,setForm]=useState({name:user.name||"",target_role:user.target_role||"",weekly_hours:user.weekly_hours||8,learning_goal:user.learning_goal||"Job Ready"}); const [roles,setRoles]=useState([]),[stats,setStats]=useState({}),[saving,setSaving]=useState(false),[msg,setMsg]=useState(""),[error,setError]=useState("");
 useEffect(()=>{Promise.all([getRoles(),getMe(),getCurrentSkillGap().catch(()=>null),getCurrentRoadmap().catch(()=>null)]).then(([r,m,g,rm])=>{setRoles(r);setForm({name:m.name,target_role:m.target_role||"",weekly_hours:m.weekly_hours||8,learning_goal:m.learning_goal||"Job Ready"});setStats({gap:g,roadmap:rm})}).catch(e=>setError(e.message))},[]);
 const save=async e=>{e.preventDefault();setSaving(true);setMsg("");try{const u=await updateProfile({...form,weekly_hours:Number(form.weekly_hours)});user.updateUser(u);setMsg("Profile saved.")}catch(e){setError(e.message)}finally{setSaving(false)}};
 const skills=stats.gap?.skills?.length||0, progress=stats.roadmap?.phases?.flatMap(p=>p.skills.flatMap(s=>s.tasks||[])).filter(t=>t.done).length||0, total=stats.roadmap?.phases?.flatMap(p=>p.skills.flatMap(s=>s.tasks||[])).length||0;
 return <main className="min-h-[calc(100vh-68px)] bg-[#fafafa]"><div className="mx-auto max-w-5xl px-5 py-10"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-indigo-600">YOUR SPACE</p><h1 className="mt-2 font-serif text-4xl font-bold">Profile</h1><p className="mt-2 text-sm text-gray-500">These preferences shape future assessments and roadmaps.</p></div>
 <div className="mt-7 grid gap-5 lg:grid-cols-[1fr_300px]"><form onSubmit={save} className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-3 border-b pb-5"><UserCircle size={38} className="text-indigo-600"/><div><p className="font-semibold">{user.email}</p><p className="text-xs text-gray-400">Account profile</p></div></div><div className="mt-6 grid gap-5 md:grid-cols-2"><Field label="Name"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="input"/></Field><Field label="Target role"><select value={form.target_role} onChange={e=>setForm({...form,target_role:e.target.value})} className="input"><option value="">Choose later</option>{roles.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></Field><Field label="Weekly learning time"><input type="number" min="1" max="40" value={form.weekly_hours} onChange={e=>setForm({...form,weekly_hours:e.target.value})} className="input"/></Field><Field label="Primary goal"><select value={form.learning_goal} onChange={e=>setForm({...form,learning_goal:e.target.value})} className="input"><option>Job Ready</option><option>Internship</option><option>Placement / Interview</option><option>Deep Mastery</option><option>Portfolio</option></select></Field></div>{error&&<p className="mt-4 rounded-lg bg-red-50 p-3 text-xs text-red-600">{error}</p>}{msg&&<p className="mt-4 rounded-lg bg-green-50 p-3 text-xs text-green-700">{msg}</p>}<button disabled={saving} className="mt-6 flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Save size={15}/>{saving?"Saving…":"Save profile"}</button></form>
 <aside className="space-y-4"><Card icon={<Target/>} label="AI-resilience" value={stats.gap?.ai_resilience_score!=null?`${stats.gap.ai_resilience_score}/100`:"Not assessed"}/><Card icon={<Sparkles/>} label="Skills assessed" value={skills||"—"}/><Card icon={<Clock3/>} label="Roadmap progress" value={total?`${Math.round(progress/total*100)}%`:"Not started"}/><button onClick={()=>nav("/history")} className="w-full rounded-xl border bg-white p-4 text-left text-sm font-semibold hover:border-indigo-200">Open assessment & roadmap history →</button></aside></div></div></main>
}
function Field({label,children}){return <label className="block text-xs font-semibold text-gray-600"><span className="mb-2 block">{label}</span>{children}</label>}
function Card({icon,label,value}){return <div className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-2 text-indigo-600">{icon && <span className="[&>svg]:h-4 [&>svg]:w-4">{icon}</span>}<span className="text-xs font-semibold">{label}</span></div><p className="mt-3 text-2xl font-bold">{value}</p></div>}
