import { useEffect,useState } from "react";
import { useNavigate,Link } from "react-router-dom";
import { ArrowRight,BrainCircuit,RotateCcw,Network,Info } from "lucide-react";
import { getCurrentSkillGap,reanalyze } from "../services/api";
import { useUser } from "../context/UserContext";
const depthClass={MASTER:"bg-gray-900 text-white","AI-AUGMENT":"bg-indigo-600 text-white","BASIC-AWARENESS":"bg-gray-200 text-gray-700"};
export default function ResultsPage(){
 const {updateUser}=useUser(),nav=useNavigate(); const [data,setData]=useState(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{getCurrentSkillGap().then(r=>{setData(r);updateUser({sessionId:r.session_id,roleId:r.role_id})}).catch(e=>setError(e.message))},[]);
 const newAssessment=async()=>{setBusy(true);try{const r=await reanalyze(data.session_id);nav(`/chat?role=${r.role_id}`)}catch(e){setError(e.message)}finally{setBusy(false)}};
 if(error)return <main className="mx-auto max-w-4xl px-5 py-14"><div className="rounded-xl border bg-white p-8"><h1 className="font-serif text-2xl font-bold">Your skill gap isn't ready yet.</h1><p className="mt-2 text-sm text-gray-500">{error}</p><Link to="/chat" className="mt-5 inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Start assessment <ArrowRight size={14}/></Link></div></main>;
 if(!data)return <main className="p-10 text-sm text-gray-500">Loading your saved skill gap…</main>;
 const coverage=data.score_breakdown.skill_coverage??data.score_breakdown.breadth??0;
 return <main className="min-h-[calc(100vh-68px)] bg-[#fafafa]"><div className="mx-auto max-w-6xl px-5 py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-indigo-600">YOUR SKILL GAP</p><h1 className="mt-3 font-serif text-4xl font-bold">{data.role} profile</h1><p className="mt-2 max-w-2xl text-sm text-gray-500">AI-resilience measures human-core ownership, AI supervision ability and how broadly you cover the role's important skill areas.</p></div><div className="rounded-2xl border bg-white px-7 py-5 text-center shadow-sm"><div className="text-5xl font-bold text-indigo-600">{data.ai_resilience_score}</div><div className="mt-1 text-[10px] font-bold uppercase tracking-widest text-gray-400">AI-resilience</div></div></div>
 <div className="mt-6 rounded-2xl border bg-white p-5"><div className="flex items-center gap-2"><BrainCircuit size={18} className="text-indigo-600"/><h2 className="text-sm font-bold">How the score works</h2><span title="Directional learning metric, not an employment prediction"><Info size={14} className="text-gray-400"/></span></div><p className="mt-2 text-xs leading-5 text-gray-500">55% human-core readiness + 30% AI-supervision readiness + 15% skill coverage. Skill coverage means how many core skill areas you have reached a working threshold in.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><ScorePart label="Human-core" value={data.score_breakdown.human_core} weight="55%"/><ScorePart label="AI supervision" value={data.score_breakdown.ai_supervision} weight="30%"/><ScorePart label="Skill coverage" value={coverage} weight="15%"/></div></div>
 <div className="mt-6 grid gap-4 md:grid-cols-4"><Stat label="At / above target" value={data.summary.at_or_above_target}/><Stat label="Human-core gaps" value={data.summary.need_real_depth}/><Stat label="Skill areas covered" value={data.score_breakdown.skill_coverage_label||`${Math.round(coverage)}%`}/><Stat label="Biggest lever" value={data.biggest_lever}/></div>
 <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_320px]"><section><div className="mb-4 flex items-center gap-2"><Network size={18} className="text-indigo-600"/><h2 className="font-serif text-2xl font-bold">Skill map</h2></div><div className="grid gap-3 md:grid-cols-2">{data.skills.map(s=><article key={s.name} className="rounded-xl border bg-white p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-semibold">{s.name}</h3><p className="mt-1 text-xs text-gray-500">{s.tier}</p></div><span className={`rounded px-2 py-1 text-[9px] font-bold ${depthClass[s.depth_call]}`}>{s.depth_call}</span></div><div className="mt-4 flex justify-between text-[10px] text-gray-400"><span>You {s.your_level_pct}%</span><span>Target {s.role_target_pct}%</span></div><div className="relative mt-1 h-2 rounded-full bg-gray-100"><div className="h-full rounded-full bg-gray-900" style={{width:`${Math.min(s.your_level_pct,100)}%`}}/><div className="absolute top-[-3px] h-4 w-0.5 bg-indigo-600" style={{left:`${Math.min(s.role_target_pct,100)}%`}}/></div><p className="mt-3 text-xs leading-5 text-gray-500">{s.note}</p></article>)}</div></section>
 <aside className="h-fit rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">What next?</p><h2 className="mt-2 font-serif text-2xl font-bold">{data.biggest_lever}</h2><p className="mt-2 text-sm leading-6 text-gray-500">This is your largest measured gap, so the roadmap gives it priority.</p><button onClick={()=>nav("/roadmap")} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-gray-900 py-3 text-sm font-semibold text-white">Open roadmap <ArrowRight size={15}/></button><button onClick={newAssessment} disabled={busy} className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl border py-3 text-sm font-semibold disabled:opacity-50"><RotateCcw size={14}/>{busy?"Starting…":"Re-assess me"}</button><p className="mt-3 text-[10px] leading-4 text-gray-400">Re-assessment creates a new saved assessment; this one remains available in history.</p></aside></div></div></main>;
}
function Stat({label,value}){return <div className="rounded-xl border bg-white p-5"><p className="truncate text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-gray-500">{label}</p></div>}
function ScorePart({label,value,weight}){return <div className="rounded-xl bg-gray-50 p-3"><div className="flex justify-between text-xs font-semibold"><span>{label}</span><span>{value}% · {weight}</span></div><div className="mt-2 h-1.5 rounded-full bg-gray-200"><div className="h-full rounded-full bg-indigo-600" style={{width:`${value}%`}}/></div></div>}
