import { useEffect,useState } from "react";
import { Link,useNavigate } from "react-router-dom";
import { ArrowRight,CheckCircle2,AlertTriangle } from "lucide-react";
import { getSkillGap } from "../services/api";
import { useUser } from "../context/UserContext";

const depthClass={MASTER:"bg-gray-900 text-white", "AI-AUGMENT":"bg-indigo-600 text-white", "BASIC-AWARENESS":"bg-gray-200 text-gray-700"};
export default function ResultsPage(){const {sessionId}=useUser();const nav=useNavigate();const [data,setData]=useState(null);const [error,setError]=useState("");useEffect(()=>{if(sessionId)getSkillGap(sessionId).then(setData).catch(e=>setError(e.message));else setError("No completed analysis yet.");},[sessionId]);if(error)return <main className="mx-auto max-w-4xl px-5 py-14"><div className="rounded-xl border bg-white p-8"><h1 className="font-serif text-2xl font-bold">Your analysis isn't ready yet.</h1><p className="mt-2 text-sm text-gray-500">{error}</p><Link to="/explore" className="mt-5 inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Choose a role <ArrowRight size={14}/></Link></div></main>;if(!data)return <main className="mx-auto max-w-4xl p-10 text-sm text-gray-500">Loading your analysis…</main>;
 return <main className="min-h-[calc(100vh-68px)] bg-[#fafafa]"><div className="mx-auto max-w-6xl px-5 py-10"><p className="text-xs font-bold uppercase tracking-[.16em] text-indigo-600">STEP 3 · YOUR SKILL GAP</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-serif text-4xl font-bold">Your {data.role} profile</h1><p className="mt-2 text-sm text-gray-500">The score is a directional calibration, not a hiring prediction.</p></div><div className="rounded-2xl border bg-white px-6 py-4 text-center"><div className="text-4xl font-bold text-indigo-600">{data.futureproof_score}</div><div className="text-[10px] font-bold uppercase tracking-widest text-gray-400">FutureProof score</div></div></div>
 <div className="mt-7 grid gap-4 md:grid-cols-3"><Stat label="At / above target" value={data.summary.at_or_above_target}/><Stat label="Master-depth gaps" value={data.summary.need_real_depth}/><Stat label="Already past target" value={data.summary.already_past_target}/></div>
 <div className="mt-8 grid gap-6 md:grid-cols-[1fr_300px]"><section><h2 className="font-serif text-2xl font-bold">Skill-by-skill gap</h2><div className="mt-4 space-y-3">{data.skills.map(s=><article key={s.name} className="rounded-xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-sm font-semibold">{s.name}</h3><p className="mt-1 text-xs text-gray-500">{s.tier}</p></div><span className={`rounded px-2 py-1 text-[9px] font-bold ${depthClass[s.depth_call]}`}>{s.depth_call}</span></div><div className="mt-4 flex justify-between text-[10px] text-gray-400"><span>Your level {s.your_level_pct}%</span><span>Target {s.role_target_pct}%</span></div><div className="relative mt-1 h-2 rounded-full bg-gray-100"><div className="h-full rounded-full bg-gray-900" style={{width:`${Math.min(s.your_level_pct,100)}%`}}/><div className="absolute top-[-3px] h-4 w-0.5 bg-indigo-600" style={{left:`${Math.min(s.role_target_pct,100)}%`}}/></div><p className="mt-3 text-xs leading-5 text-gray-500">{s.note}</p></article>)}</div></section><aside className="h-fit rounded-xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-indigo-600"><AlertTriangle size={17}/><span className="text-xs font-bold uppercase tracking-wider">Biggest lever</span></div><h2 className="mt-3 font-serif text-2xl font-bold">{data.biggest_lever}</h2><p className="mt-2 text-sm leading-6 text-gray-500">This is the largest measured gap in your current calibration, so it gets priority in the roadmap.</p><button onClick={()=>nav("/roadmap")} className="mt-6 flex w-full items-center justify-center gap-2 rounded-lg bg-gray-900 py-3 text-sm font-semibold text-white">Build my roadmap <ArrowRight size={15}/></button></aside></div></div></main>;
}
function Stat({label,value}){return <div className="rounded-xl border bg-white p-5"><p className="text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-gray-500">{label}</p></div>}
