import { useEffect,useMemo,useState } from "react";
import { useNavigate } from "react-router-dom";
import { BookOpen,Clock3,CheckCircle2,Circle,GitBranch,RefreshCw,Settings2,ArrowRight,CalendarDays,MessageSquareText } from "lucide-react";
import { adaptRoadmap,createRoadmap,getCurrentRoadmap,updateRoadmapProgress } from "../services/api";
import { useUser } from "../context/UserContext";
export default function RoadmapPage(){
 const {updateUser}=useUser(),nav=useNavigate(); const [data,setData]=useState(null),[error,setError]=useState(""),[duration,setDuration]=useState(3),[goal,setGoal]=useState("Job Ready"),[hours,setHours]=useState(8),[showAdapt,setShowAdapt]=useState(false),[reason,setReason]=useState(""),[details,setDetails]=useState(""),[saving,setSaving]=useState(false);
 useEffect(()=>{getCurrentRoadmap().then(r=>{setData(r);setDuration(r.duration_months);setGoal(r.goal);setHours(r.weekly_hours);updateUser({sessionId:r.assessment_id})}).catch(e=>setError(e.message))},[]);
 const allTasks=useMemo(()=>data?.phases?.flatMap(p=>p.skills.flatMap(s=>s.tasks||[]))||[],[data]); const completed=allTasks.filter(t=>t.done).length,progress=allTasks.length?Math.round(completed/allTasks.length*100):0;
 const regenerate=async()=>{if(!data)return;setSaving(true);try{const r=await createRoadmap(data.assessment_id,{duration_months:Number(duration),goal,weekly_hours:Number(hours)});setData({...r,assessment_id:data.assessment_id});}catch(e){setError(e.message)}finally{setSaving(false)}};
 const adapt=async()=>{if(!data)return;setSaving(true);try{const r=await adaptRoadmap(data.assessment_id,{reason,details});setData({...r,assessment_id:data.assessment_id});setShowAdapt(false);setReason("");setDetails("")}catch(e){setError(e.message)}finally{setSaving(false)}};
 const toggle=async task=>{try{const r=await updateRoadmapProgress(data.assessment_id,task.id,!task.done);setData({...r,assessment_id:data.assessment_id})}catch(e){setError(e.message)}};
 if(error)return <main className="mx-auto max-w-5xl p-10"><div className="rounded-2xl border bg-white p-8"><h1 className="font-serif text-2xl font-bold">Roadmap unavailable</h1><p className="mt-2 text-sm text-gray-500">{error}</p><button onClick={()=>nav("/chat")} className="mt-5 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Start assessment</button></div></main>;
 if(!data)return <main className="p-10 text-sm text-gray-500">Loading your saved roadmap…</main>;
 return <main className="min-h-[calc(100vh-68px)] bg-[#fafafa]"><div className="mx-auto max-w-7xl px-5 py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-indigo-600">YOUR LEARNING JOURNEY</p><h1 className="mt-3 font-serif text-4xl font-bold">Your {data.duration_months}-month roadmap</h1><p className="mt-2 text-sm text-gray-500">{data.role} · {data.goal} · {data.weekly_hours} hrs/week</p></div><div className="flex gap-2"><button onClick={()=>setShowAdapt(true)} className="flex items-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold"><MessageSquareText size={15}/> Adapt roadmap</button><button onClick={()=>nav("/skill-gap")} className="flex items-center gap-2 rounded-xl bg-gray-900 px-4 py-2.5 text-sm font-semibold text-white">Reassess <RefreshCw size={14}/></button></div></div>
 <div className="mt-7 grid gap-4 lg:grid-cols-[1fr_320px]"><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-gray-400">Overall progress</p><p className="mt-1 text-3xl font-bold">{progress}% <span className="text-sm font-normal text-gray-400">· {completed}/{allTasks.length} tasks</span></p></div><div className="w-full max-w-md"><div className="h-3 rounded-full bg-gray-100"><div className="h-full rounded-full bg-indigo-600 transition-all" style={{width:`${progress}%`}}/></div></div></div></section><section className="rounded-2xl border bg-indigo-50 p-5"><p className="text-xs font-bold text-indigo-700">Roadmap design</p><p className="mt-2 text-sm leading-6 text-indigo-900/70">Follow the flow from foundation → applied skills → proof of work. Resources sit inside every skill node.</p></section></div>
 <div className="mt-4 rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center gap-4"><div className="flex items-center gap-2 text-xs font-semibold"><CalendarDays size={15} className="text-indigo-600"/> Duration</div>{[3,6,9,12].map(x=><button key={x} onClick={()=>setDuration(x)} className={`rounded-full border px-3 py-1.5 text-xs font-semibold ${duration===x?"border-indigo-600 bg-indigo-50 text-indigo-700":"bg-white text-gray-600"}`}>{x} months</button>)}<input type="number" min="1" max="24" value={duration} onChange={e=>setDuration(Number(e.target.value))} className="w-24 rounded-full border px-3 py-1.5 text-xs"/><span className="text-[10px] text-gray-400">Custom months</span><select value={goal} onChange={e=>setGoal(e.target.value)} className="rounded-full border px-3 py-1.5 text-xs"><option>Job Ready</option><option>Internship</option><option>Placement / Interview</option><option>Deep Mastery</option><option>Portfolio</option></select><label className="text-xs font-semibold">{hours}h/week <input type="range" min="1" max="40" value={hours} onChange={e=>setHours(Number(e.target.value))} className="ml-2 align-middle"/></label><button onClick={regenerate} disabled={saving} className="rounded-xl bg-indigo-600 px-4 py-2 text-xs font-semibold text-white disabled:opacity-50">{saving?"Updating…":"Apply plan"}</button></div></div>
 <div className="mt-8 overflow-x-auto pb-4"><div className="min-w-[900px]"><div className="mb-7 flex items-center justify-center"><div className="rounded-2xl border-2 border-indigo-200 bg-indigo-50 px-8 py-4 text-center"><p className="text-[10px] font-bold uppercase tracking-widest text-indigo-600">TARGET</p><p className="mt-1 font-serif text-xl font-bold">{data.role} · {data.goal}</p></div></div><div className="mx-auto h-8 w-px bg-gray-300"/>
 <div className="relative grid grid-cols-3 gap-6">{data.phases.map((p,i)=><div key={p.phase_number} className="relative">{i<2&&<div className="absolute right-[-24px] top-10 z-0 h-px w-12 bg-gray-300"/>}<div className="relative z-10 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="rounded-full bg-gray-100 px-2 py-1 text-[10px] font-bold">PHASE {p.phase_number}</span><GitBranch size={15} className="text-indigo-500"/></div><h2 className="mt-3 font-serif text-xl font-bold">{p.title}</h2><p className="mt-1 text-xs text-gray-400">Days {p.days}</p><div className="mt-4 space-y-2">{p.skills.map(s=><div key={s.name} className="rounded-xl bg-gray-50 p-3"><div className="flex items-center justify-between gap-2"><p className="text-xs font-semibold">{s.name}</p><span className="text-[10px] text-gray-400">{s.hours_per_week}h/w</span></div><div className="mt-2 h-1.5 rounded-full bg-gray-200"><div className="h-full rounded-full bg-indigo-500" style={{width:`${Math.round((s.tasks.filter(t=>t.done).length/s.tasks.length)*100)}%`}}/></div><div className="mt-2 flex items-center justify-between"><span className="text-[10px] text-gray-400">{s.tasks.filter(t=>t.done).length}/{s.tasks.length} tasks</span><a href={s.resource_url} target="_blank" rel="noreferrer" className="flex items-center gap-1 text-[10px] font-semibold text-indigo-600"><BookOpen size={11}/>{s.resource}</a></div></div>)}</div></div></div>)}</div></div></div>
 <div className="mt-8 grid gap-5 lg:grid-cols-2">{data.phases.map(p=><section key={p.phase_number} className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-widest text-indigo-600">Phase {p.phase_number}</p><h2 className="mt-1 font-serif text-xl font-bold">{p.title}</h2></div><span className="text-xs text-gray-400">Days {p.days}</span></div><div className="mt-4 space-y-4">{p.skills.map(s=><article key={s.name} className="rounded-xl border p-4"><div className="flex items-start justify-between"><div><h3 className="text-sm font-semibold">{s.name}</h3><p className="mt-1 text-xs text-gray-500">{s.tier} · {s.hours_per_week}h/week</p></div></div><div className="mt-3 space-y-1">{s.tasks.map(t=><button key={t.id} onClick={()=>toggle(t)} className="flex w-full items-center gap-2 rounded-lg px-2 py-2 text-left text-xs hover:bg-gray-50">{t.done?<CheckCircle2 size={15} className="text-indigo-600"/>:<Circle size={15} className="text-gray-300"/>}<span className={t.done?"text-gray-400 line-through":"text-gray-700"}>{t.title}</span></button>)}</div><a href={s.resource_url} target="_blank" rel="noreferrer" className="mt-3 flex items-center gap-1 text-xs font-semibold text-indigo-600"><BookOpen size={13}/>{s.resource}</a></article>)}</div></section>)}</div>
 {showAdapt&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-5"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-indigo-600">ADAPT ROADMAP</p><h2 className="mt-1 font-serif text-2xl font-bold">Tell SkillPilot what changed</h2></div><button onClick={()=>setShowAdapt(false)} className="text-gray-400">✕</button></div><div className="mt-5 grid gap-2">{["I have less time now","I have more time now","I am struggling with a skill","I already know some topics","I want more projects","My career goal changed"].map(x=><button key={x} onClick={()=>setReason(x)} className={`rounded-xl border px-3 py-2 text-left text-xs ${reason===x?"border-indigo-500 bg-indigo-50 text-indigo-700":"hover:bg-gray-50"}`}>{x}</button>)}</div><textarea value={details} onChange={e=>setDetails(e.target.value)} placeholder="For example: I have exams for the next month, so I can only study 4 hours/week. After that I can return to 10 hours." className="mt-4 min-h-28 w-full rounded-xl border p-3 text-sm outline-none focus:border-indigo-500"/><p className="mt-2 text-[10px] text-gray-400">The AI can translate your situation into a new duration, weekly load and goal. Your completed tasks are preserved.</p><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setShowAdapt(false)} className="rounded-xl border px-4 py-2 text-sm">Cancel</button><button disabled={!reason||saving} onClick={adapt} className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">{saving?"Rebuilding…":"Rebuild roadmap"}</button></div></div></div>}
 </div></main>;
}
