import { useEffect,useState } from "react";
import { Link,useNavigate,useParams } from "react-router-dom";
import { ArrowLeft,ArrowRight } from "lucide-react";
import { getRole } from "../services/api";
import { useUser } from "../context/UserContext";

const styles={"Human-Core":"border-green-200 bg-green-50 text-green-700","AI-Augmented":"border-yellow-200 bg-yellow-50 text-yellow-700","AI-Accelerated":"border-red-200 bg-red-50 text-red-600"};
export default function RoleDetailPage(){const {roleId}=useParams();const nav=useNavigate();const {setSession}=useUser();const [role,setRole]=useState(null);const [error,setError]=useState("");useEffect(()=>{getRole(roleId).then(setRole).catch(e=>setError(e.message));},[roleId]);if(error)return <main className="mx-auto max-w-4xl p-10"><p className="text-red-600">{error}</p><Link to="/explore" className="mt-4 inline-block text-indigo-600">← Back</Link></main>;if(!role)return <main className="mx-auto max-w-4xl p-10 text-sm text-gray-500">Loading role…</main>;
const start=()=>{setSession({role:role.title,roleId:role.id});nav(`/chat?role=${role.id}`)};
return <main className="min-h-[calc(100vh-68px)] bg-[#fafafa]"><div className="mx-auto max-w-5xl px-5 py-10"><Link to="/explore" className="flex items-center gap-2 text-sm text-gray-500"><ArrowLeft size={15}/> All roles</Link><div className="mt-7 grid gap-8 md:grid-cols-[1fr_320px]"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-indigo-600">{role.onet_soc_code} · O*NET evidence</p><h1 className="mt-3 font-serif text-4xl font-bold">{role.title}</h1><p className="mt-4 text-sm leading-6 text-gray-500">{role.description}</p><h2 className="mt-10 font-serif text-2xl font-bold">What the role does</h2><ul className="mt-4 space-y-3">{role.responsibilities.map(x=><li key={x} className="rounded-lg border bg-white p-4 text-sm text-gray-600">{x}</li>)}</ul></div><aside className="h-fit rounded-xl border bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-widest text-gray-400">Depth framework</p><p className="mt-3 text-sm leading-6 text-gray-500">Not every skill deserves the same learning investment. SkillPilot classifies each one by the depth worth building in an AI-heavy workflow.</p><button onClick={start} className="mt-6 flex w-full items-center justify-center gap-2 rounded-lg bg-indigo-600 py-3 text-sm font-semibold text-white hover:bg-indigo-700">Calibrate my skills <ArrowRight size={15}/></button></aside></div><div className="mt-10"><h2 className="font-serif text-2xl font-bold">Skill depth map</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{role.skills.map(s=><div key={s.name} className="rounded-xl border bg-white p-5"><div className="flex items-start justify-between gap-3"><h3 className="text-sm font-semibold">{s.name}</h3><span className={`rounded-full border px-2 py-1 text-[9px] font-bold ${styles[s.tier]}`}>{s.tier}</span></div><div className="mt-3 inline-block rounded bg-gray-900 px-2 py-1 text-[10px] font-bold text-white">{s.depth}</div><p className="mt-3 text-xs leading-5 text-gray-500">{s.note}</p></div>)}</div></div></div></main>;
}
